compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: false
  zero_stage: 2
distributed_type: DEEPSPEED 
# distributed_type: MULTI_GPU
downcast_bf16: 'fp16'
gpu_ids: all
machine_rank: 0
main_process_ip: 192.168.5.11 
main_process_port: 10086  
main_training_function: main
mixed_precision: 'fp16' 
num_machines: 2  
num_processes: 2 
rdzv_backend: static
same_network: True
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false